apiVersion: demon.io/v1
kind: AppPack
metadata:
  name: hoss
  version: 0.1.0
  description: Hedgehog Operational Support System - Fabric topology validation for Hedgehog Open Network Fabric
  repository: https://github.com/afewell-hh/hoss
  license: Apache-2.0

signing:
  cosign:
    enabled: true

compatibility:
  appPackSchema: ">=1.0,<2.0"
  platformAPI: ">=1.0,<2.0"

contracts:
  - id: hoss/validate.request
    version: 0.1.0
    path: contracts/hoss/validate.request.json
  - id: hoss/validate.result
    version: 0.1.0
    path: contracts/hoss/validate.result.json

capsules:
  - type: container-exec
    name: hhfab
    imageDigest: ghcr.io/afewell-hh/hoss/hhfab@sha256:54814bbf4e8459cfb35c7cf8872546f0d5d54da9fc317ffb53eab0e137b21d7b
    command: ["/bin/bash", "-c", "set -Eeuo pipefail; /workspace/capsules/hhfab/scripts/hhfab-validate.sh"]
    env:
      TMPDIR: /tmp
      HHFAB_CACHE_DIR: /tmp/.hhfab-cache
      HOME: /tmp
      HISTFILE: /dev/null
      BASH_ENV: ""
      SHELL: /bin/bash
    outputs:
      envelopePath: /workspace/.artifacts/summary.json
    sandbox:
      network: none
      readOnly: true
      tmpfs:
        - /tmp
      securityOpt:
        - no-new-privileges

rituals:
  - name: hoss-validate
    description: Validate Hedgehog fabric wiring diagram using hhfab
    steps:
      - capsule: hhfab
        with: {}

ui:
  cards:
    - id: hoss-validate-card
      kind: result-envelope
      title: HOSS Validation
      description: Fabric topology validation results
      match:
        rituals: ["hoss-validate"]
      fields:
        show:
          - status
          - counts.validated
          - counts.warnings
          - counts.failures
          - tool.version
          - tool.imageDigest
