apiVersion: demon.io/v1
kind: UICard
metadata:
  id: hoss-validate-card
  name: HOSS Validation
  description: Fabric topology validation results from hhfab

spec:
  kind: result-envelope

  match:
    rituals:
      - hoss-validate

  display:
    title: "HOSS Fabric Validation"
    icon: "check-circle"
    color:
      ok: green
      warning: yellow
      error: red

  fields:
    - path: result.data.status
      label: Status
      type: badge
      mapping:
        ok: Success
        warning: Warning
        error: Failed

    - path: result.data.counts.validated
      label: Diagrams Validated
      type: number

    - path: result.data.counts.warnings
      label: Warnings
      type: number
      highlight: true

    - path: result.data.counts.failures
      label: Failures
      type: number
      highlight: true

    - path: result.data.tool.version
      label: Tool Version
      type: text

    - path: result.data.tool.imageDigest
      label: Image Digest
      type: digest
      truncate: 12

    - path: result.data.timestamp
      label: Validated At
      type: timestamp

  sections:
    - title: Validation Details
      fields:
        - result.data.status
        - result.data.counts.validated
        - result.data.counts.warnings
        - result.data.counts.failures

    - title: Tool Information
      fields:
        - result.data.tool.version
        - result.data.tool.imageDigest
        - result.data.timestamp

    - title: Validated Files
      collapsible: true
      field: result.data.matrix
      type: list
