name: hhfab validate (canary)
description: Minimal composite that writes a valid review-kit summary.json without running hhfab.
author: HOSS Automation
inputs:
  strict:
    description: Simulate strict mode
    required: false
    default: 'true'
  mode:
    description: passthrough mode
    required: false
    default: ''
  matrix:
    description: passthrough matrix
    required: false
    default: ''
  use-container:
    description: passthrough use-container
    required: false
    default: 'false'
  container-image:
    description: passthrough container-image
    required: false
    default: ''

outputs:
  summary_path:
    description: Path to the generated summary.json
    value: ${{ steps.write.outputs.summary_path }}

runs:
  using: composite
  steps:
    - name: Prep artifacts dir
      shell: bash
      run: |
        set -Eeuo pipefail
        install -d -m 0777 .artifacts/review-kit

    - id: write
      name: Write canary summary
      shell: bash
      run: |
        set -Eeuo pipefail
        SUMMARY=".artifacts/review-kit/summary.json"
        jq -n --arg strict "${{ inputs.strict }}" --arg hhfd "$HHFAB_IMAGE_DIGEST" --arg sha "$GITHUB_SHA" --arg ref "$GITHUB_REF" '
          {
            status: "ok",
            strict: ($strict == "true"),
            counts: { validated: 1, warnings: 0, failures: 0 },
            image: { digest: ($hhfd // "absent") },
            hhfab: { tool: "hhfab", version: "canary" },
            env: { githubSha: $sha, ref: $ref }
          }
        ' > "$SUMMARY"
        echo "summary_path=$(pwd)/$SUMMARY" >> "$GITHUB_OUTPUT"

    - name: Show summary path
      shell: bash
      run: |
        set -Eeuo pipefail
        echo "summary_path=$(pwd)/.artifacts/review-kit/summary.json"
        jq . .artifacts/review-kit/summary.json || true

