name: label: enforce-hhfab
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: cf
        with:
          filters: |
            hhfab:
              - 'contracts/**'
              - 'samples/**'
      - uses: actions/github-script@v7
        with:
          script: |
            const has = ${{ steps.cf.outputs.hhfab == 'true' }};
            const { owner, repo } = context.repo;
            const issue_number = context.payload.number;
            const label = 'enforce-hhfab';
            const labels = (await github.rest.issues.listLabelsOnIssue({ owner, repo, issue_number })).data.map(l => l.name);
            if (has && !labels.includes(label)) {
              await github.rest.issues.addLabels({ owner, repo, issue_number, labels: [label] });
            } else if (!has && labels.includes(label)) {
              await github.rest.issues.removeLabel({ owner, repo, issue_number, name: label }).catch(() => {});
            }
