name: label-hhfab
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Detect hhfab sensitive changes
        id: changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            hhfab:
              - 'samples/**'
              - 'contracts/**'
              - 'scripts/**'
              - '.github/actions/**'
      - name: Apply hhfab-sensitive label
        if: steps.changes.outputs.hhfab == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const label = 'hhfab-sensitive';
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;

            async function ensureLabelExists() {
              try {
                await github.rest.issues.getLabel({ owner, repo, name: label });
              } catch (error) {
                if (error.status !== 404) throw error;
                await github.rest.issues.createLabel({
                  owner,
                  repo,
                  name: label,
                  color: '5319e7',
                  description: 'Changes touch hhfab validation or samples'
                });
              }
            }

            await ensureLabelExists();
            await github.rest.issues.addLabels({ owner, repo, issue_number, labels: [label] });
