name: shellcheck
run-name: "shellcheck @ ${{ github.sha }}"

on:
  pull_request:
    paths:
      - 'scripts/**/*.sh'
      - '.github/workflows/shellcheck.yml'
  push:
    branches: [main]
    paths:
      - 'scripts/**/*.sh'
      - '.github/workflows/shellcheck.yml'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # 2.0.0
        with:
          scandir: './scripts'
          severity: error
          format: gcc

      - name: Summary
        if: always()
        run: |
          echo "### Shellcheck Results" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "✅ All shell scripts passed shellcheck" >> "$GITHUB_STEP_SUMMARY"
