name: Validate Action Pins

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

permissions:
  contents: read

jobs:
  validate-pins:
    name: Check SHA-pinned Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Validate all actions are SHA-pinned
        run: |
          set -euo pipefail

          echo "🔍 Scanning workflows for unpinned actions..."

          # Find all workflow files
          WORKFLOWS=$(find .github/workflows -name "*.yml" -o -name "*.yaml" 2>/dev/null || true)
          ACTIONS=$(find .github/actions -name "*.yml" -o -name "*.yaml" 2>/dev/null || true)

          ALL_FILES="$WORKFLOWS $ACTIONS"

          if [ -z "$ALL_FILES" ]; then
            echo "⚠️  No workflow or action files found"
            exit 0
          fi

          # Track unpinned actions
          UNPINNED=0
          UNPINNED_LIST=""

          for file in $ALL_FILES; do
            # Skip empty results
            [ -f "$file" ] || continue

            # Look for uses: lines with @vX.Y.Z or @vX patterns (not SHA-pinned)
            MATCHES=$(grep -n "uses:.*@v[0-9]" "$file" || true)

            if [ -n "$MATCHES" ]; then
              echo "❌ Found unpinned actions in $file:"
              echo "$MATCHES" | while read -r line; do
                echo "    $line"
              done
              UNPINNED=$((UNPINNED + 1))
              UNPINNED_LIST="$UNPINNED_LIST\n  - $file"
            fi
          done

          if [ $UNPINNED -gt 0 ]; then
            echo ""
            echo "❌ FAILURE: Found $UNPINNED file(s) with unpinned actions"
            echo ""
            echo "All GitHub Actions must be pinned to a specific SHA for security."
            echo ""
            echo "Example of correct pinning:"
            echo "  uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2"
            echo ""
            echo "Files with unpinned actions:"
            echo -e "$UNPINNED_LIST"
            echo ""
            echo "Dependabot will keep these pins updated automatically."
            exit 1
          fi

          echo "✅ All actions are SHA-pinned"
